In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

 # Numpy
   
   **NumPy (Numerical Python)** is an open source Python library that’s used in almost every field of science and engineering.The NumPy library contains multidimensional array and matrix data structures. It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it. NumPy can be used to perform a wide variety of mathematical operations on arrays.
     


  **Import and version**

In [23]:
#import numpy as np and see the version

import numpy as np
print(np.__version__)

1.26.4


**Dimension,Shape,Size of the array**

In [20]:
#dimension,shape,size and type

print("x3 ndim: ", a1.ndim)
print("x3 shape:", a1.shape)
print("x3 size: ", a1.size)
print("type:", type(a))

x3 ndim:  2
x3 shape: (3, 4)
x3 size:  12
type: <class 'numpy.ndarray'>


**Create 1D and Multidimensional array**

In [9]:
#creating a 1D array,

a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [8]:
#Creating Multidimensional array

a1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a1)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**Arange**

In [34]:
# print integers from 0 to 10

x = np.arange(10)
print(x)


[0 1 2 3 4 5 6 7 8 9]


In [35]:
x = np.arange(4,10)  # np.arange(start, stop)
print(x)

[4 5 6 7 8 9]


In [36]:
x = np.arange(1,14,3)   # np.arange(start,stop,step)
print(x)

[ 1  4  7 10 13]


**Reshaping of Arrays**

In [27]:
#Reshaping
#converting 1D  array to 2D array

arr = np.arange(10)
arr.reshape(2, -1)  # Setting to -1 automatically decides the number of cols




array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
#reshaping into 3x3 

grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Zeros,Ones and Full**

In [32]:
#Zeros,Ones and Full

# 3 x 4 ndarray full of zeros
# np.zeros(shape)
x = np.zeros((3,4))
print(x)

# a 3 x 2 ndarray full of ones
# np.ones(shape)
y = np.ones((3,2))
print(y)

# 2 x 3 ndarray full of fives
# np.full(shape, constant value)
z = np.full((2,3), 5)
print(z)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[5 5 5]
 [5 5 5]]


**Linspace**

In [37]:
#The np.linspace() function is used to create an array of evenly spaced numbers within a specified range.

i = np.linspace(10,40,7)
print(i)
     

[10. 15. 20. 25. 30. 35. 40.]


**Identity Matrix**

In [39]:
# 5 x 5 Identity matrix
X = np.eye(5)
X

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**Accessing the Array Elements**

In [16]:
#Accessing the array elements

#a=np.array([1,2,3,4,5])

print(a[1])      #1D
print(a[-1])    #using negative indices

#In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

#a1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(a1[1,2])   


2
7
5


**Array Slicing - 1D**

In [41]:
#syntax:  arr[start:stop:step]

#(:) It is called as slice notation used to access the subarrays

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [43]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [44]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [45]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [46]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [47]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [48]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

**Array Slicing-Multidimensional**

In [51]:
x1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(x)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [52]:
x1[:2, :3]  # two rows, three columns

array([[1, 2, 3],
       [5, 6, 7]])

In [53]:
x1[:3, ::2]  # all rows, every other column

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [54]:
x1[::-1, ::-1]

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [55]:
print(x1[:, 0])  # first column of x2

[1 5 9]


In [56]:
print(x1[0, :])  # first row of x2

[1 2 3 4]


**Unique Elements**

In [59]:
u = np.unique(x)


**Array Concatenation and Splitting**

In [60]:
#concatenation of arrays
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [61]:
#splitting of arrays
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


**Sorting**

In [63]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [64]:
#argsort returns  the indices of the sorted elements
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)

[1 0 3 2 4]


**Mathematical Operations on Numpy Array**

In [65]:
x = np.random.randint(0,10,(4,4))
y = np.random.randint(10,20,(4,4))
print(x)
print(y)

[[0 9 7 7]
 [3 6 9 7]
 [1 2 6 9]
 [0 2 6 9]]
[[19 15 16 11]
 [14 13 19 17]
 [18 16 12 18]
 [13 10 10 11]]


In [69]:
#addition
print(x+y)

#np.add(x,y)

[[19 24 23 18]
 [17 19 28 24]
 [19 18 18 27]
 [13 12 16 20]]


In [70]:
#subtraction
print(x-y)

#np.subtract(x,y)

[[-19  -6  -9  -4]
 [-11  -7 -10 -10]
 [-17 -14  -6  -9]
 [-13  -8  -4  -2]]


In [71]:
#multiplication
print(x*y)

#np.multiply(x,y)

[[  0 135 112  77]
 [ 42  78 171 119]
 [ 18  32  72 162]
 [  0  20  60  99]]


In [72]:
#division
print(x/y)

#np.divide(x,y)

[[0.         0.6        0.4375     0.63636364]
 [0.21428571 0.46153846 0.47368421 0.41176471]
 [0.05555556 0.125      0.5        0.5       ]
 [0.         0.2        0.6        0.81818182]]


**Transpose**

In [73]:
array = np.random.randint(0,10,(2,3))
print(array)
array.shape

[[7 3 1]
 [4 0 6]]


(2, 3)

In [74]:

#transpose
trans = np.transpose(array)
print(trans)
trans.shape

[[7 4]
 [3 0]
 [1 6]]


(3, 2)